import { WorkersRecordDTO } from "../models/WorkersRecordDTO";

export function getWorkersRecords() {
  let arr: WorkersRecordDTO[] = [
    {
      RecordNo: "1",
      Notes: "ملاحظات",
      ContractNo: "1",
      SettlementNo: "1",
      Workers: [
        {
          ID: "1",
          Name: "محمد شوقي احمد",
          NationalID: "25408190101111",
          Occupation: "نجار",
          Address: "شبرا الخيمة",
          PhoneNo: "02-44624212",
          WorkersRecordNo: "1",
        },
        {
          ID: "2",
          Name: "مصطفي سيد علي",
          NationalID: "26408190101112",
          Occupation: "حداد",
          Address: "رمسيس",
          PhoneNo: "02-46614512",
          WorkersRecordNo: "1",
        },
        {
          ID: "3",
          Name: "طارق مصطفي سليمان",
          NationalID: "27408190101176",
          Occupation: "نجار",
          Address: "الوراق",
          PhoneNo: "02-44614712",
          WorkersRecordNo: "1",
        },
        {
          ID: "4",
          Name: "علاء السيد محمد",
          NationalID: "28402190101431",
          Occupation: "سباك",
          Address: "امبابة",
          PhoneNo: "02-44418412",
          WorkersRecordNo: "1",
        },
        {
          ID: "5",
          Name: "خالد محمود عبد الله",
          NationalID: "28401190101221",
          Occupation: "نقاش",
          Address: "الجمالية",
          PhoneNo: "02-44114412",
          WorkersRecordNo: "1",
        },
        {
          ID: "6",
          Name: "منير احمد الجمال",
          NationalID: "28403190101221",
          Occupation: "بناء",
          Address: "شبرا",
          PhoneNo: "02-44314412",
          WorkersRecordNo: "1",
        },
      ],
    },
    {
      RecordNo: "2",
      Notes: "ملاحظات",
      ContractNo: "2",
      SettlementNo: "2",
      Workers: [
        {
          ID: "1",
          Name: "محمدجمال  احمد",
          NationalID: "25408190101111",
          Occupation: "نجار",
          Address: "شبرا الخيمة",
          PhoneNo: "02-44624212",
          WorkersRecordNo: "2",
        },
        {
          ID: "2",
          Name: "طارق سيد علي",
          NationalID: "26408190101112",
          Occupation: "حداد",
          Address: "رمسيس",
          PhoneNo: "02-46614512",
          WorkersRecordNo: "2",
        },
        {
          ID: "3",
          Name: "منير مصطفي السيد",
          NationalID: "27408190101176",
          Occupation: "نجار",
          Address: "الوراق",
          PhoneNo: "02-44614712",
          WorkersRecordNo: "2",
        },
        {
          ID: "4",
          Name: "صلاح السيد عارف",
          NationalID: "28402190101431",
          Occupation: "سباك",
          Address: "امبابة",
          PhoneNo: "02-44418412",
          WorkersRecordNo: "2",
        },
        {
          ID: "5",
          Name: "مصطفي جمال عبد الله",
          NationalID: "28401190101221",
          Occupation: "نقاش",
          Address: "الجمالية",
          PhoneNo: "02-44114412",
          WorkersRecordNo: "2",
        },
      ],
    },
  ];
  return arr;
}
